podResources:
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

extraPodConfig:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 50

container:
  pullPolicy: Always
  port: #yourport

hpa:
  required: false
